title: Site
unlisted: true

tabs:
  pages:
    label:
      de: Seiten
      en: Pages
    sections:
      drafts:
        type: pages
        status: draft
        headline:
          de: Entwürfe
          en: Drafts
      published:
        type: pages
        status: published
        headline:
          de: Veröffentlicht
          en: Published
        sortable: true
  settings:
    label:
      de: Einstellungen
      en: Settings
    fields:
      menus:
        label:
          de: Menüs
          en: Menus
        type: structure
        fields:
          menuHeadline:
            type: text
            label: Menu headline
          menuItems:
            type: pages
            label: Menu item
            status: all
      qr_campaigns:
        label:
          de: QR-Code Kampagnen
          en: QR-Code Campaigns
        type: structure
        columns:
          slug:
            width: 1/5
          targetPage:
            width: 2/5
          targetUrl:
            width: 2/5
        fields:
          slug:
            type: text
          externalUrl:
            type: toggle
            text:
              -
                en: "Internal page"
                de: "Interne Seite"
              -
                en: "External URL"
                de: "Externe URL"
          targetPage:
            type: pages
            multiple: false
            when:
              externalUrl: false
          targetUrl:
            type: url
            when:
              externalUrl: true
