type: group
fields:
  navTitle:
    label:
      de: Link-Titel
      en: Link title
    type: text
    help:
      de: F端r Men端s
      en: F端r menus
  description:
    label:
      de: Kurzbeschreibung
      en: Description
    type: textarea
    size: small
    help:
      de: F端r Suchmaschinen und Social Media. Im besten Fall unter 160 Zeichen.
      en: For search engines and social media. Keep below 160 characters.
